### ISSUE TITLE
UI is not getting updated even after client sends message

### ISSUE THREAD

**Issue by durka1109** [one-quick/one-quick#2]
![1](https://user-images.githubusercontent.com/103326172/229290834-99805b18-563a-459e-b62e-d792ccc541f1.png)
![2](https://user-images.githubusercontent.com/103326172/229290839-67d12381-3608-478a-a27b-ec7a4eb4e08b.png)
![3](https://user-images.githubusercontent.com/103326172/229290841-58c0ad6c-329a-4e8a-a621-917e9a2f091f.png)
![4](https://user-images.githubusercontent.com/103326172/229290845-ba3a5f85-f9dd-4acb-b4b2-e54d6d250c5f.png)

**Comment by ELAKKIYA-R** [comment]
solved it with c59d4d6
